#!/bin/bash
CMD_START_EXTENSION="java -jar /opt/selenium/cerberus-robot-extension.jar -p ${CERBERUS_ROBOT_EXTENSION_PORT:-6555} -d"

if [ -n "$CERBERUS_ROBOT_EXTENSION_HIGHLIGHT_ELEMENT" ]; then
CMD_START_EXTENSION="$CMD_START_EXTENSION -e $CERBERUS_ROBOT_EXTENSION_HIGHLIGHT_ELEMENT"
fi

if [ -n "$CERBERUS_ROBOT_EXTENSION_AUTHORIZED_FOLDER_SCOPE" ]; then
CMD_START_EXTENSION="$CMD_START_EXTENSION -a $CERBERUS_ROBOT_EXTENSION_AUTHORIZED_FOLDER_SCOPE"
fi

if [ -n "$CERBERUS_ROBOT_EXTENSION_DEBUG" ]; then
CMD_START_EXTENSION="$CMD_START_EXTENSION -d"
fi

eval $CMD_START_EXTENSION