#!/bin/bash
CMD_START_JAVA="java -Djava.awt.headless=false "

if [ -n "$CERBERUS_ROBOT_EXTENSION_HIGHLIGHT_ELEMENT" ]; then
CRB_START_EXTENSION="$CRB_START_EXTENSION -e $CERBERUS_ROBOT_EXTENSION_HIGHLIGHT_ELEMENT"
fi

if [ -n "$CERBERUS_ROBOT_EXTENSION_AUTHORIZED_FOLDER_SCOPE" ]; then
CRB_START_EXTENSION="$CRB_START_EXTENSION -a $CERBERUS_ROBOT_EXTENSION_AUTHORIZED_FOLDER_SCOPE"
fi

if [ -n "$CERBERUS_ROBOT_EXTENSION_DEBUG" ]; then
CRB_START_EXTENSION="$CRB_START_EXTENSION -d"
CMD_START_JAVA="$CMD_START_JAVA  -Dlog.level=DEBUG -Xmx1024m "
fi

CMD_START_EXTENSION="$CMD_START_JAVA -jar /opt/selenium/cerberus-robot-extension.jar -p ${CERBERUS_ROBOT_EXTENSION_PORT:-6555} $CRB_START_EXTENSION"
echo "Starting Cerberus Extension : " $CMD_START_EXTENSION
eval $CMD_START_EXTENSION
