# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to QA

on:
  push:
    branches: [ master ]
  # temporary disabled due to qa deployements during unmerged pull requests
  # pull_request:
  #  branches: [ master ]

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install --file pom.xml
    - name: Push file to core VM
      env:
        source-jar: 'target/*.jar'
        destination: 'debian@vm.cerberus-testing.org:/opt/delivery/'  
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        sudo rsync -chav \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          ${{env.source-jar}} ${{env.destination}}

